# normal force regulation PI gains
controller/alpha_p: 0.0 #0.0022
controller/alpha_i: 0.0 #0.00022

# trajectory position control gain
controller/alpha: 0.0

# desired normal force [N]
controller/f_d: 10.0

# control frequency [Hz]
controller/control_freq: 150.0

# trajectory type 
trajectory_generator/trajectory_type: circle

# trajectory duration [s]
trajectory_generator/duration: 8.0

# trajectory radius [m]
trajectory_generator/radius: 0.05

# trajectory period [s]
trajectory_generator/period: 8.0